name: Java CI Workflow

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
permissions:  
  contents: read
  security-events: write
  
jobs:
  ci-workflow-java:
    uses: Agnaldo-Cavaleiro/workflow-reutilizable-demo/.github/workflows/java-reutilizable-ci.yml@main
    with:
      artifact-name: 'Package-tokiota'
      java-version:  '17'
      distribution : 'corretto'
